### ISSUE TITLE
use of undeclared identifier 'NID_stark256v1'

### ISSUE THREAD

**Issue by louisliu2048** [Safeheron/safeheron-crypto-suites-cpp#4]
[  6%] Building C object CMakeFiles/SafeheronCryptoSuites.dir/src/crypto-curve-cpp/src/crypto-curve/ed25519_ex.c.o
[  6%] Building CXX object CMakeFiles/SafeheronCryptoSuites.dir/src/crypto-curve-cpp/src/crypto-curve/curve.cpp.o
/Users/louisliu/golang/src/github.com/mpc/Safeheron/safeheron-crypto-suites-cpp/src/crypto-curve-cpp/src/crypto-curve/curve.cpp:115:68: error: use of undeclared identifier 'NID_stark256v1'
            if (!stark_grp) stark_grp = EC_GROUP_new_by_curve_name(NID_stark256v1);
                                                                   ^
1 error generated.
make[2]: *** [CMakeFiles/SafeheronCryptoSuites.dir/src/crypto-curve-cpp/src/crypto-curve/curve.cpp.o] Error 1
make[1]: *** [CMakeFiles/SafeheronCryptoSuites.dir/all] Error 2
make: *** [all] Error 2
>  build git:(stark_curve)

**Comment by sword03** [comment]
Use the "stark_curve" branch.
https://github.com/Safeheron/safeheron-crypto-suites-cpp/tree/stark_curve

And install the openssl refer to  https://github.com/Safeheron/safeheron-crypto-suites-cpp/blob/stark_curve/doc/OpenSSL-Installation.md

**Comment by louisliu2048** [comment]
<img width="391" alt="image" src="https://user-images.githubusercontent.com/35095310/232433363-7330166b-753c-4a2f-a396-7a89e3524988.png">

it's already stark_curve!

**Comment by sword03** [comment]
Install the openssl refer to https://github.com/Safeheron/safeheron-crypto-suites-cpp/blob/stark_curve/doc/OpenSSL-Installation.md

The StarkCurve is not supported by OpenSSL. We have extended OpenSSL to support the StarkCurve. If you want to use the StarkCurve, you must install the [OpenSSL extended by Safeheron](https://github.com/Safeheron/openssl/tree/stark_curve) (refer to the "stark_curve" branch). Otherwise, you will get an error when you use the StarkCurve.

**Comment by louisliu2048** [comment]
そうか
